@base_url =  http://localhost:3000

### GET ALL
GET {{base_url}}/tasks

### COUNT
GET {{base_url}}/tasks/count

### GET ONE
GET {{base_url}}/tasks/1

### CREATE
POST {{base_url}}/tasks
Content-Type: application/json

{
    "title": "Third task",
    "description": "Description of the third task"
}

### DELETE
DELETE {{base_url}}/tasks/1

### UPDATE
PUT {{base_url}}/tasks/6
Content-Type: application/json

{
    "title": "Tarea",
    "description": "Descripción tarea"
}